// US States and cities organized by state
// Cities with population over 30,000

export const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'District of Columbia',
] as const

export const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa', 'Dothan', 'Auburn', 'Bessemer', 'Anniston', 'Gadsden'],
  Alaska: ['Anchorage', 'Juneau', 'Fairbanks'],
  Arizona: ['Phoenix', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert', 'Tempe', 'Peoria', 'Tucson', 'Ahwatukee', 'Surprise', 'Avondale', 'Goodyear', 'Lake Havasu City', 'Flagstaff', 'Yuma'],
  Arkansas: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro', 'North Little Rock', 'Conway', 'Rogers', 'Bentonville', 'Pine Bluff', 'Texarkana'],
  California: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Irvine', 'Chula Vista', 'Playa Vista', 'Moreno Valley', 'Fontana', 'Santa Clarita', 'Huntington Beach', 'Modesto', 'Glendale', 'Ontario', 'Santa Rosa', 'Oxnard', 'Victorville', 'Vallejo', 'Berkeley', 'Fremont', 'Salinas', 'Pasadena', 'Hayward', 'Escondido', 'Garden Grove', 'Torrance', 'Daly City', 'Fairfield', 'Visalia', 'Fullerton', 'Inglewood', 'Palmdale', 'Concord', 'Sunnyvale', 'Downey', 'Oceanside', 'Redding', 'Vacaville', 'Chico', 'Roseville', 'Antioch', 'Elk Grove'],
  Colorado: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminister', 'Pueblo', 'Centennial', 'Boulder', 'Greeley', 'Longmont', 'Loveland', 'Castle Rock', 'Grand Junction'],
  Connecticut: ['Bridgeport', 'New Haven', 'Hartford', 'Waterbury', 'Norwalk', 'Stamford', 'Danbury', 'New Britain', 'Bristol', 'Meriden'],
  Delaware: ['Wilmington', 'Dover'],
  Florida: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Tallahassee', 'Port St. Lucie', 'Fort Lauderdale', 'Cape Coral', 'Fort Myers', 'West Palm Beach', 'Lakeland', 'Gainesville', 'Coral Springs', 'Miami Gardens', 'Clearwater', 'Deerfield Beach', 'Pembroke Pines', 'Hollywood', 'Miramar', 'Boca Raton', 'Pompano Beach', 'Palm Bay', 'Bradenton', 'Sarasota', 'Sunrise', 'Delray Beach', 'Largo', 'Naples', 'Davie', 'Kissimmee', 'Ocala', 'Pinellas Park', 'Jacksonville Beach', 'Riviera Beach', 'Daytona Beach', 'Weston', 'Coconut Creek', 'Leesburg', 'St. Augustine', 'Tamarac', 'Aventura'],
  Georgia: ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Athens', 'Macon', 'Marietta', 'Sandy Springs', 'Roswell', 'Valdosta', 'Alpharetta', 'Peachtree City', 'Dalton', 'Smyrna', 'Johns Creek', 'Dunwoody', 'Kennesaw', 'Decatur', 'Cumming', 'Douglasville'],
  Hawaii: ['Honolulu', 'Kailua', 'Kaneohe', 'Waipahu', 'Mililani', 'Kapolei', 'Kihei', 'Lahaina'],
  Idaho: ['Boise', 'Meridian', 'Pocatello', 'Idaho Falls', 'Nampa', 'Caldwell', 'Twin Falls', 'Coeur d''Alene'],
  Illinois: ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Naperville', 'Springfield', 'Peoria', 'Elgin', 'Waukegan', 'Cicero', 'Arlington Heights', 'Evanston', 'Downers Grove', 'Schaumburg', 'Bolingbrook', 'Des Plaines', 'Decatur', 'Skokie', 'Champaign', 'Oak Lawn', 'Tinley Park', 'Oak Park', 'Palatine', 'Wheaton', 'Lombard', 'Berwyn', 'Quincy', 'Urbana', 'Mount Prospect', 'Normal', 'Hoffman Estates', 'Carol Stream', 'Bloomingdale', 'Barrington'],
  Indiana: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Mishawaka', 'Bloomington', 'Muncie', 'Lafayette', 'Gary', 'Hammond', 'Terre Haute', 'Anderson', 'Kokomo', 'Carmel', 'Fishers', 'Greenwood'],
  Iowa: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Iowa City', 'Dubuque', 'Waterloo', 'Sioux City', 'Ames', 'Council Bluffs', 'Bettendorf', 'Ankeny'],
  Kansas: ['Kansas City', 'Wichita', 'Overland Park', 'Topeka', 'Olathe', 'Lawrence', 'Salina', 'Manhattan', 'Leawood', 'Shawnee', 'Lenexa'],
  Kentucky: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Hopkinsville', 'Paducah', 'Henderson', 'Ashland', 'Frankfort'],
  Louisiana: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles', 'Kenner', 'Alexandria', 'Monroe', 'Metairie', 'Marrero', 'Houma'],
  Maine: ['Portland', 'Lewiston', 'Bangor'],
  Maryland: ['Baltimore', 'Columbia', 'Frederick', 'Gaithersburg', 'Rockville', 'Bowie', 'Annapolis', 'Glen Burnie', 'Towson', 'Dundalk', 'Ellicott City'],
  Massachusetts: ['Boston', 'Worcester', 'Springfield', 'Lowell', 'Cambridge', 'New Bedford', 'Brockton', 'Quincy', 'Lynn', 'Fall River', 'Newton', 'Somerville', 'Lawrence', 'Framingham', 'Waltham', 'Malden', 'Medford', 'Weymouth', 'Revere'],
  Michigan: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Lansing', 'Ann Arbor', 'Flint', 'Dearborn', 'Livonia', 'Westland', 'Farmington Hills', 'Kalamazoo', 'Taylor', 'Southfield', 'Dearborn Heights', 'Troy', 'Pontiac', 'Saginaw', 'Jackson', 'Inkster', 'Battle Creek', 'Wyandotte', 'Canton', 'Clinton Township', 'Muskegon', 'Roseville', 'Eastpointe'],
  Minnesota: ['Minneapolis', 'St. Paul', 'Rochester', 'Bloomington', 'Duluth', 'St. Cloud', 'Mankato', 'Maple Grove', 'Edina', 'Plymouth', 'St. Louis Park', 'Coon Rapids', 'Burnsville', 'Eden Prairie', 'Minnetonka', 'Maplewood', 'Eagan', 'Rosemont', 'Fridley', 'Richfield'],
  Mississippi: ['Jackson', 'Gulfport', 'Biloxi', 'Hattiesburg', 'Meridian', 'Greenville', 'Tupelo'],
  Missouri: ['Kansas City', 'St. Louis', 'Springfield', 'Independence', 'Columbia', 'St. Joseph', 'Joplin', 'Lee''s Summit', 'O''Fallon', 'Florissant', 'St. Peters', 'Raytown', 'Blue Springs', 'University City', 'Chesterfield', 'Kirkwood', 'Mexico'],
  Montana: ['Billings', 'Missoula', 'Great Falls', 'Bozeman'],
  Nebraska: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Fremont'],
  Nevada: ['Las Vegas', 'Henderson', 'North Las Vegas', 'Reno', 'Sparks', 'Carson City', 'Elko'],
  'New Hampshire': ['Manchester', 'Nashua', 'Portsmouth'],
  'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton', 'Camden', 'Atlantic City', 'Clifton', 'Irvington', 'Jersey Shore', 'Hackensack', 'Edison', 'Woodbridge', 'Paramus', 'Union', 'Passaic', 'Bayonne', 'East Orange', 'Plainfield', 'Bergenfield', 'Englewood', 'Guttenberg', 'New Brunswick', 'Perth Amboy', 'Vineland', 'Asbury Park', 'Hoboken', 'Secaucus', 'Fort Lee'],
  'New Mexico': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe'],
  'New York': ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady', 'Utica', 'Watertown', 'Niagara Falls', 'Binghamton', 'Troy', 'Rome', 'Plattsburgh', 'Newburgh', 'Port Chester'],
  'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Wilmington', 'Durham', 'Winston-Salem', 'Fayetteville', 'Cary', 'Chapel Hill', 'Greenville', 'High Point', 'Asheboro', 'Goldsboro', 'Rocky Mount', 'Concord', 'Kannapolis'],
  'North Dakota': ['Bismarck', 'Fargo', 'Grand Forks'],
  Ohio: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma', 'Youngstown', 'Canton', 'Lorain', 'Elyria', 'Hamilton', 'Warren', 'Kettering', 'Findlay', 'Mansfield', 'Cuyahoga Falls', 'Springfield', 'Lakewood', 'Euclid', 'Middletown', 'Athens', 'Westerville', 'Wooster', 'Medina'],
  Oklahoma: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond', 'Midwest City', 'Lawton', 'Enid', 'Stillwater', 'Muskogee'],
  Oregon: ['Portland', 'Eugene', 'Salem', 'Gresham', 'Hillsboro', 'Beaverton', 'Medford', 'Springfield', 'Bend', 'Corvallis', 'Grants Pass', 'Tigard'],
  Pennsylvania: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton', 'Bethlehem', 'Lancaster', 'Harrisburg', 'Altoona', 'York', 'Wilkes-Barre', 'Chester', 'Sunbury', 'Hazleton'],
  'Rhode Island': ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
  'South Carolina': ['Charleston', 'Columbia', 'Greenville', 'Florence', 'Myrtle Beach', 'Spartanburg', 'North Charleston', 'Sumter', 'Aiken'],
  'South Dakota': ['Sioux Falls', 'Rapid City'],
  Tennessee: ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Franklin', 'Jackson', 'Johnson City', 'Bristol', 'Kingsport', 'Oak Ridge'],
  Texas: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Garland', 'Lubbock', 'Laredo', 'Irving', 'Chandler', 'Amarillo', 'Frisco', 'McKinney', 'Grapevine', 'Brownsville', 'Carrollton', 'Denton', 'Beaumont', 'Lewisville', 'Round Rock', 'Port Arthur', 'New Braunfels', 'Killeen', 'Waco', 'Abilene', 'San Marcos', 'San Angelo', 'Mesquite', 'Odessa', 'Midland', 'Tyler', 'Longview', 'Richardson', 'Pasadena', 'Pearland', 'Wichita Falls', 'Allen', 'Prairie View', 'Galveston', 'Bryan', 'College Station', 'Conroe', 'Temple', 'Pflugerville', 'Brownwood', 'Lufkin', 'Corsicana', 'Nacogdoches'],
  Utah: ['Salt Lake City', 'Provo', 'West Valley City', 'Orem', 'Sandy', 'Ogden', 'Lehi', 'American Fork', 'Layton', 'Saint George', 'Logan', 'Draper', 'Bountiful', 'Farmington', 'Payson'],
  Vermont: ['Burlington', 'Montpelier'],
  Virginia: ['Richmond', 'Virginia Beach', 'Norfolk', 'Alexandria', 'Arlington', 'Roanoke', 'Newport News', 'Arlington County', 'Hampton', 'Charlottesville', 'Lynchburg', 'Blacksburg', 'Falls Church', 'Leesburg', 'Winchester'],
  Washington: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Puyallup', 'Federal Way', 'Auburn', 'Yakima', 'Bellingham', 'Sammamish', 'Redmond', 'Shoreline', 'Kirkland', 'Edmonds', 'Bremerton', 'Burien', 'Marysville', 'Olympia'],
  'West Virginia': ['Charleston', 'Huntington', 'Wheeling', 'Morgantown', 'Parkersburg'],
  Wisconsin: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Waukesha', 'Eau Claire', 'Sheboygan', 'West Milwaukee', 'Oshkosh'],
  Wyoming: ['Cheyenne', 'Casper', 'Laramie'],
  'District of Columbia': ['Washington'],
}
