// US States and cities organized by state
// Cities with population over 30,000

export const US_STATES = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'District of Columbia',
] as const

export const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa', 'Dothan', 'Auburn', 'Bessemer', 'Anniston', 'Gadsden'],
  Alaska: ['Anchorage', 'Juneau', 'Fairbanks'],
  Arizona: ['Phoenix', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert', 'Tempe', 'Peoria', 'Tucson', 'Ahwatukee', 'Surprise', 'Avondale', 'Goodyear', 'Lake Havasu City', 'Flagstaff', 'Yuma'],
  Arkansas: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro', 'North Little Rock', 'Conway', 'Rogers', 'Bentonville', 'Pine Bluff', 'Texarkana'],
  California: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Irvine', 'Chula Vista', 'Playa Vista', 'Moreno Valley', 'Fontana', 'Santa Clarita', 'Huntington Beach', 'Modesto', 'Glendale', 'Ontario', 'Santa Rosa', 'Oxnard', 'Victorville', 'Vallejo', 'Berkeley', 'Fremont', 'Salinas', 'Pasadena', 'Hayward', 'Escondido', 'Garden Grove', 'Torrance', 'Daly City', 'Fairfield', 'Visalia', 'Fullerton', 'Inglewood', 'Palmdale', 'Concord', 'Sunnyvale', 'Downey', 'Oceanside', 'Redding', 'Vacaville', 'Chico', 'Roseville', 'Antioch', 'Elk Grove'],
  Colorado: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminister', 'Pueblo', 'Centennial', 'Boulder', 'Greeley', 'Longmont', 'Loveland', 'Castle Rock', 'Grand Junction'],
  Connecticut: ['Bridgeport', 'New Haven', 'Hartford', 'Waterbury', 'Norwalk', 'Stamford', 'Danbury', 'New Britain', 'Bristol', 'Meriden'],
  Delaware: ['Wilmington', 'Dover'],
  Florida: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Tallahassee', 'Port St. Lucie', 'Fort Lauderdale', 'Cape Coral', 'Fort Myers', 'West Palm Beach', 'Lakeland', 'Gainesville', 'Coral Springs', 'Miami Gardens', 'Clearwater', 'Deerfield Beach', 'Pembroke Pines', 'Hollywood', 'Miramar', 'Boca Raton', 'Pompano Beach', 'Palm Bay', 'Bradenton', 'Sarasota', 'Sunrise', 'Delray Beach', 'Largo', 'Naples', 'Davie', 'Kissimmee', 'Ocala', 'Pinellas Park', 'Jacksonville Beach', 'Riviera Beach', 'Daytona Beach', 'Weston', 'Coconut Creek', 'Leesburg', 'St. Augustine', 'Tamarac', 'Aventura'],
  Georgia: ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Athens', 'Macon', 'Marietta', 'Sandy Springs', 'Roswell', 'Valdosta', 'Alpharetta', 'Peachtree City', 'Dalton', 'Smyrna', 'Johns Creek', 'Dunwoody', 'Kennesaw', 'Decatur', 'Cumming', 'Douglasville'],
  Hawaii: ['Honolulu', 'Kailua', 'Kaneohe', 'Waipahu', 'Mililani', 'Kapolei', 'Kihei', 'Lahaina'],
  Idaho: ['Boise', 'Meridian', 'Pocatello', 'Idaho Falls', 'Nampa', 'Caldwell', 'Twin Falls', 'Coeur d\'Alene'],
  Illinois: ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Naperville', 'Springfield', 'Peoria', 'Elgin', 'Waukegan', 'Cicero', 'Arlington Heights', 'Evanston', 'Downers Grove', 'Schaumburg', 'Bolingbrook', 'Des Plaines', 'Decatur', 'Skokie', 'Champaign', 'Oak Lawn', 'Tinley Park', 'Oak Park', 'Palatine', 'Wheaton', 'Lombard', 'Berwyn', 'Quincy', 'Urbana', 'Mount Prospect', 'Normal', 'Hoffman Estates', 'Carol Stream', 'Bloomingdale', 'Barrington'],
  Indiana: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Mishawaka', 'Bloomington', 'Muncie', 'Lafayette', 'Gary', 'Hammond', 'Terre Haute', 'Anderson', 'Kokomo', 'Carmel', 'Fishers', 'Greenwood'],
  Iowa: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Iowa City', 'Dubuque', 'Waterloo', 'Sioux City', 'Ames', 'Council Bluffs', 'Bettendorf', 'Ankeny'],
  Kansas: ['Kansas City', 'Wichita', 'Overland Park', 'Topeka', 'Olathe', 'Lawrence', 'Salina', 'Manhattan', 'Leawood', 'Shawnee', 'Lenexa'],
  Kentucky: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Hopkinsville', 'Paducah', 'Henderson', 'Ashland', 'Frankfort'],
  Louisiana: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles', 'Kenner', 'Alexandria', 'Monroe', 'Metairie', 'Marrero', 'Houma'],
  Maine: ['Portland', 'Lewiston', 'Bangor'],
  Maryland: ['Baltimore', 'Columbia', 'Frederick', 'Gaithersburg', 'Rockville', 'Bowie', 'Annapolis', 'Glen Burnie', 'Towson', 'Dundalk', 'Ellicott City'],
  Massachusetts: ['Boston', 'Worcester', 'Springfield', 'Lowell', 'Cambridge', 'New Bedford', 'Brockton', 'Quincy', 'Lynn', 'Fall River', 'Newton', 'Somerville', 'Lawrence', 'Framingham', 'Waltham', 'Malden', 'Medford', 'Weymouth', 'Revere'],
  Michigan: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Lansing', 'Ann Arbor', 'Flint', 'Dearborn', 'Livonia', 'Westland', 'Farmington Hills', 'Kalamazoo', 'Taylor', 'Southfield', 'Dearborn Heights', 'Troy', 'Pontiac', 'Saginaw', 'Jackson', 'Inkster', 'Battle Creek', 'Wyandotte', 'Canton', 'Clinton Township', 'Muskegon', 'Roseville', 'Eastpointe'],
  Minnesota: ['Minneapolis', 'St. Paul', 'Rochester', 'Bloomington', 'Duluth', 'St. Cloud', 'Mankato', 'Maple Grove', 'Edina', 'Plymouth', 'St. Louis Park', 'Coon Rapids', 'Burnsville', 'Eden Prairie', 'Minnetonka', 'Maplewood', 'Eagan', 'Rosemont', 'Fridley', 'Richfield'],
  Mississippi: ['Jackson', 'Gulfport', 'Biloxi', 'Hattiesburg', 'Meridian', 'Greenville', 'Tupelo'],
  Missouri: ['Kansas City', 'St. Louis', 'Springfield', 'Independence', 'Columbia', 'St. Joseph', 'Joplin', 'Lee\'s Summit', 'O\'Fallon', 'Florissant', 'St. Peters', 'Raytown', 'Blue Springs', 'University City', 'Chesterfield', 'Kirkwood', 'Mexico'],
  Montana: ['Billings', 'Missoula', 'Great Falls', 'Bozeman'],
  Nebraska: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Fremont'],
  Nevada: ['Las Vegas', 'Henderson', 'North Las Vegas', 'Reno', 'Sparks', 'Carson City', 'Elko'],
  'New Hampshire': ['Manchester', 'Nashua', 'Portsmouth'],
  'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Trenton', 'Camden', 'Atlantic City', 'Clifton', 'Irvington', 'Jersey Shore', 'Hackensack', 'Edison', 'Woodbridge', 'Paramus', 'Union', 'Passaic', 'Bayonne', 'East Orange', 'Plainfield', 'Bergenfield', 'Englewood', 'Guttenberg', 'New Brunswick', 'Perth Amboy', 'Vineland', 'Asbury Park', 'Hoboken', 'Secaucus', 'Fort Lee'],
  'New Mexico': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe'],
  'New York': ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady', 'Utica', 'Watertown', 'Niagara Falls', 'Binghamton', 'Troy', 'Rome', 'Plattsburgh', 'Newburgh', 'Port Chester'],
  'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Wilmington', 'Durham', 'Winston-Salem', 'Fayetteville', 'Cary', 'Chapel Hill', 'Greenville', 'High Point', 'Asheboro', 'Goldsboro', 'Rocky Mount', 'Concord', 'Kannapolis'],
  'North Dakota': ['Bismarck', 'Fargo', 'Grand Forks'],
  Ohio: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma', 'Youngstown', 'Canton', 'Lorain', 'Elyria', 'Hamilton', 'Warren', 'Kettering', 'Findlay', 'Mansfield', 'Cuyahoga Falls', 'Springfield', 'Lakewood', 'Euclid', 'Middletown', 'Athens', 'Westerville', 'Wooster', 'Medina'],
  Oklahoma: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond', 'Midwest City', 'Lawton', 'Enid', 'Stillwater', 'Muskogee'],
  Oregon: ['Portland', 'Eugene', 'Salem', 'Gresham', 'Hillsboro', 'Beaverton', 'Medford', 'Springfield', 'Bend', 'Corvallis', 'Grants Pass', 'Tigard'],
  Pennsylvania: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton', 'Bethlehem', 'Lancaster', 'Harrisburg', 'Altoona', 'York', 'Wilkes-Barre', 'Chester', 'Sunbury', 'Hazleton'],
  'Rhode Island': ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
  'South Carolina': ['Charleston', 'Columbia', 'Greenville', 'Florence', 'Myrtle Beach', 'Spartanburg', 'North Charleston', 'Sumter', 'Aiken'],
  'South Dakota': ['Sioux Falls', 'Rapid City'],
  Tennessee: ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Franklin', 'Jackson', 'Johnson City', 'Bristol', 'Kingsport', 'Oak Ridge'],
  Texas: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Garland', 'Lubbock', 'Laredo', 'Irving', 'Chandler', 'Amarillo', 'Frisco', 'McKinney', 'Grapevine', 'Brownsville', 'Carrollton', 'Denton', 'Beaumont', 'Lewisville', 'Round Rock', 'Port Arthur', 'New Braunfels', 'Killeen', 'Waco', 'Abilene', 'San Marcos', 'San Angelo', 'Mesquite', 'Odessa', 'Midland', 'Tyler', 'Longview', 'Richardson', 'Pasadena', 'Pearland', 'Wichita Falls', 'Allen', 'Prairie View', 'Galveston', 'Bryan', 'College Station', 'Conroe', 'Temple', 'Pflugerville', 'Brownwood', 'Lufkin', 'Corsicana', 'Nacogdoches'],
  Utah: ['Salt Lake City', 'Provo', 'West Valley City', 'Orem', 'Sandy', 'Ogden', 'Lehi', 'American Fork', 'Layton', 'Saint George', 'Logan', 'Draper', 'Bountiful', 'Farmington', 'Payson'],
  Vermont: ['Burlington', 'Montpelier'],
  Virginia: ['Richmond', 'Virginia Beach', 'Norfolk', 'Alexandria', 'Arlington', 'Roanoke', 'Newport News', 'Arlington County', 'Hampton', 'Charlottesville', 'Lynchburg', 'Blacksburg', 'Falls Church', 'Leesburg', 'Winchester'],
  Washington: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Puyallup', 'Federal Way', 'Auburn', 'Yakima', 'Bellingham', 'Sammamish', 'Redmond', 'Shoreline', 'Kirkland', 'Edmonds', 'Bremerton', 'Burien', 'Marysville', 'Olympia'],
  'West Virginia': ['Charleston', 'Huntington', 'Wheeling', 'Morgantown', 'Parkersburg'],
  Wisconsin: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Waukesha', 'Eau Claire', 'Sheboygan', 'West Milwaukee', 'Oshkosh'],
  Wyoming: ['Cheyenne', 'Casper', 'Laramie'],
  'District of Columbia': ['Washington'],
}

export const NEARBY_CITIES: Record<string, string[]> = {
  'Raleigh': ['Raleigh', 'Cary', 'Durham', 'Chapel Hill', 'Garner', 'Morrisville', 'Apex'],
  'Cary': ['Raleigh', 'Cary', 'Durham', 'Chapel Hill', 'Garner', 'Morrisville', 'Apex'],
  'Durham': ['Raleigh', 'Cary', 'Durham', 'Chapel Hill', 'Garner', 'Morrisville'],
  'Chapel Hill': ['Raleigh', 'Cary', 'Durham', 'Chapel Hill', 'Garner'],
  'Garner': ['Raleigh', 'Cary', 'Garner', 'Morrisville', 'Apex'],
  'Morrisville': ['Raleigh', 'Cary', 'Morrisville', 'Garner', 'Apex'],
  'Apex': ['Cary', 'Garner', 'Morrisville', 'Apex'],
  'Charlotte': ['Charlotte', 'Concord', 'Kannapolis'],
  'Concord': ['Charlotte', 'Concord', 'Kannapolis'],
  'Kannapolis': ['Charlotte', 'Concord', 'Kannapolis'],
  'Greensboro': ['Greensboro', 'High Point', 'Winston-Salem'],
  'High Point': ['Greensboro', 'High Point', 'Winston-Salem'],
  'Winston-Salem': ['Greensboro', 'High Point', 'Winston-Salem'],
  'San Francisco': ['San Francisco', 'Oakland', 'Berkeley', 'Hayward', 'Fremont'],
  'Oakland': ['San Francisco', 'Oakland', 'Berkeley', 'Hayward'],
  'Berkeley': ['San Francisco', 'Oakland', 'Berkeley'],
  'Hayward': ['Oakland', 'Hayward', 'Fremont'],
  'Fremont': ['Hayward', 'Fremont', 'San Jose'],
  'San Jose': ['Fremont', 'San Jose', 'Sunnyvale'],
  'Sunnyvale': ['San Jose', 'Sunnyvale'],
  'Los Angeles': ['Los Angeles', 'Long Beach', 'Anaheim', 'Santa Ana', 'Glendale', 'Pasadena'],
  'Long Beach': ['Los Angeles', 'Long Beach', 'Anaheim'],
  'Anaheim': ['Los Angeles', 'Long Beach', 'Anaheim', 'Santa Ana', 'Garden Grove'],
  'Santa Ana': ['Anaheim', 'Santa Ana', 'Garden Grove'],
  'Glendale': ['Los Angeles', 'Glendale', 'Pasadena'],
  'Pasadena': ['Glendale', 'Pasadena', 'Los Angeles'],
  'Garden Grove': ['Anaheim', 'Santa Ana', 'Garden Grove'],
  'Dallas': ['Dallas', 'Arlington', 'Fort Worth', 'Garland', 'Plano', 'Irving'],
  'Arlington': ['Dallas', 'Arlington', 'Fort Worth', 'Irving'],
  'Fort Worth': ['Dallas', 'Arlington', 'Fort Worth'],
  'Garland': ['Dallas', 'Garland', 'Arlington'],
  'Plano': ['Dallas', 'Plano', 'Frisco', 'McKinney'],
  'Irving': ['Dallas', 'Arlington', 'Irving'],
  'Frisco': ['Plano', 'Frisco', 'McKinney'],
  'McKinney': ['Plano', 'Frisco', 'McKinney', 'Denton'],
  'Denton': ['McKinney', 'Denton'],
  'Houston': ['Houston', 'Pasadena', 'Pearland'],
  'Pasadena': ['Houston', 'Pasadena'],
  'Pearland': ['Houston', 'Pearland'],
  'Austin': ['Austin', 'Round Rock', 'Pflugerville'],
  'Round Rock': ['Austin', 'Round Rock', 'Pflugerville'],
  'Pflugerville': ['Austin', 'Round Rock', 'Pflugerville'],
  'San Antonio': ['San Antonio', 'New Braunfels'],
  'New Braunfels': ['San Antonio', 'New Braunfels'],
  'Miami': ['Miami', 'Hialeah', 'Miami Gardens', 'Boca Raton'],
  'Hialeah': ['Miami', 'Hialeah', 'Miami Gardens'],
  'Miami Gardens': ['Miami', 'Hialeah', 'Miami Gardens'],
  'Boca Raton': ['Miami', 'Boca Raton', 'Delray Beach'],
  'Delray Beach': ['Boca Raton', 'Delray Beach'],
  'Tampa': ['Tampa', 'St. Petersburg', 'Clearwater'],
  'St. Petersburg': ['Tampa', 'St. Petersburg', 'Clearwater'],
  'Clearwater': ['Tampa', 'St. Petersburg', 'Clearwater'],
  'Orlando': ['Orlando', 'Kissimmee'],
  'Kissimmee': ['Orlando', 'Kissimmee'],
  'Jacksonville': ['Jacksonville', 'Jacksonville Beach'],
  'Jacksonville Beach': ['Jacksonville', 'Jacksonville Beach'],
  'Atlanta': ['Atlanta', 'Sandy Springs', 'Roswell', 'Alpharetta', 'Marietta', 'Decatur'],
  'Sandy Springs': ['Atlanta', 'Sandy Springs', 'Roswell'],
  'Roswell': ['Atlanta', 'Sandy Springs', 'Roswell', 'Alpharetta'],
  'Alpharetta': ['Roswell', 'Alpharetta', 'Marietta'],
  'Marietta': ['Alpharetta', 'Marietta', 'Atlanta'],
  'Decatur': ['Atlanta', 'Decatur'],
  'Chicago': ['Chicago', 'Evanston', 'Naperville', 'Schaumburg', 'Arlington Heights', 'Des Plaines'],
  'Evanston': ['Chicago', 'Evanston', 'Skokie'],
  'Naperville': ['Chicago', 'Naperville', 'Downers Grove'],
  'Schaumburg': ['Chicago', 'Schaumburg', 'Arlington Heights'],
  'Arlington Heights': ['Chicago', 'Schaumburg', 'Arlington Heights', 'Des Plaines'],
  'Des Plaines': ['Chicago', 'Arlington Heights', 'Des Plaines'],
  'Skokie': ['Chicago', 'Evanston', 'Skokie'],
  'Downers Grove': ['Naperville', 'Downers Grove'],
  'New York City': ['New York City', 'Yonkers', 'New Rochelle', 'Jersey City'],
  'Yonkers': ['New York City', 'Yonkers', 'New Rochelle'],
  'New Rochelle': ['Yonkers', 'New Rochelle'],
  'Jersey City': ['New York City', 'Jersey City', 'Newark'],
  'Newark': ['Jersey City', 'Newark', 'Elizabeth'],
  'Elizabeth': ['Newark', 'Elizabeth'],
  'Philadelphia': ['Philadelphia', 'Chester'],
  'Chester': ['Philadelphia', 'Chester'],
  'Columbus': ['Columbus', 'Westerville'],
  'Westerville': ['Columbus', 'Westerville'],
  'Cleveland': ['Cleveland', 'Parma', 'Lakewood'],
  'Parma': ['Cleveland', 'Parma'],
  'Lakewood': ['Cleveland', 'Lakewood'],
  'Cincinnati': ['Cincinnati', 'Hamilton'],
  'Hamilton': ['Cincinnati', 'Hamilton'],
  'Detroit': ['Detroit', 'Dearborn', 'Warren', 'Sterling Heights', 'Livonia'],
  'Dearborn': ['Detroit', 'Dearborn', 'Livonia'],
  'Warren': ['Detroit', 'Warren', 'Sterling Heights'],
  'Sterling Heights': ['Warren', 'Sterling Heights'],
  'Livonia': ['Detroit', 'Dearborn', 'Livonia'],
  'Seattle': ['Seattle', 'Bellevue', 'Tacoma', 'Renton', 'Edmonds', 'Redmond'],
  'Bellevue': ['Seattle', 'Bellevue', 'Redmond'],
  'Tacoma': ['Seattle', 'Tacoma'],
  'Renton': ['Seattle', 'Renton'],
  'Edmonds': ['Seattle', 'Edmonds'],
  'Redmond': ['Bellevue', 'Redmond'],
  'Denver': ['Denver', 'Aurora', 'Lakewood', 'Boulder'],
  'Aurora': ['Denver', 'Aurora'],
  'Lakewood': ['Denver', 'Lakewood'],
  'Boulder': ['Denver', 'Boulder'],
  'Phoenix': ['Phoenix', 'Mesa', 'Chandler', 'Scottsdale', 'Gilbert', 'Glendale'],
  'Mesa': ['Phoenix', 'Mesa', 'Chandler', 'Gilbert'],
  'Chandler': ['Mesa', 'Chandler', 'Gilbert', 'Phoenix'],
  'Scottsdale': ['Phoenix', 'Scottsdale', 'Glendale'],
  'Gilbert': ['Mesa', 'Chandler', 'Gilbert'],
  'Glendale': ['Phoenix', 'Scottsdale', 'Glendale'],
  'Las Vegas': ['Las Vegas', 'Henderson', 'North Las Vegas'],
  'Henderson': ['Las Vegas', 'Henderson'],
  'North Las Vegas': ['Las Vegas', 'North Las Vegas'],
  'Salt Lake City': ['Salt Lake City', 'West Valley City', 'Orem', 'Provo'],
  'West Valley City': ['Salt Lake City', 'West Valley City'],
  'Orem': ['Salt Lake City', 'Orem', 'Provo'],
  'Provo': ['Orem', 'Provo'],
  'Boston': ['Boston', 'Cambridge', 'Somerville', 'Newton', 'Waltham', 'Brookline'],
  'Cambridge': ['Boston', 'Cambridge', 'Somerville'],
  'Somerville': ['Boston', 'Cambridge', 'Somerville'],
  'Newton': ['Boston', 'Newton', 'Waltham'],
  'Waltham': ['Newton', 'Waltham'],
  'Baltimore': ['Baltimore', 'Columbia', 'Towson'],
  'Columbia': ['Baltimore', 'Columbia'],
  'Towson': ['Baltimore', 'Towson'],
  'Minneapolis': ['Minneapolis', 'St. Paul', 'Bloomington', 'St. Louis Park', 'Edina'],
  'St. Paul': ['Minneapolis', 'St. Paul', 'Bloomington'],
  'Bloomington': ['Minneapolis', 'St. Paul', 'Bloomington', 'Eden Prairie'],
  'St. Louis Park': ['Minneapolis', 'St. Louis Park'],
  'Edina': ['Minneapolis', 'Edina'],
  'Eden Prairie': ['Bloomington', 'Eden Prairie'],
  'Kansas City': ['Kansas City', 'Independence', 'Lee\'s Summit', 'Blue Springs'],
  'Independence': ['Kansas City', 'Independence'],
  'Lee\'s Summit': ['Kansas City', 'Lee\'s Summit', 'Blue Springs'],
  'Blue Springs': ['Lee\'s Summit', 'Blue Springs'],
  'St. Louis': ['St. Louis', 'St. Peters', 'Florissant', 'University City'],
  'St. Peters': ['St. Louis', 'St. Peters'],
  'Florissant': ['St. Louis', 'Florissant'],
  'University City': ['St. Louis', 'University City'],
  'Nashville': ['Nashville', 'Franklin'],
  'Franklin': ['Nashville', 'Franklin'],
  'Memphis': ['Memphis'],
  'Wilmington': ['Wilmington', 'Greenville'],
  'Greenville': ['Wilmington', 'Greenville'],
  'Indianapolis': ['Indianapolis', 'Carmel', 'Fishers'],
  'Carmel': ['Indianapolis', 'Carmel', 'Fishers'],
  'Fishers': ['Carmel', 'Fishers'],
  'Bridgeport': ['Bridgeport', 'Norwalk'],
  'Norwalk': ['Bridgeport', 'Norwalk', 'Stamford'],
  'Stamford': ['Norwalk', 'Stamford'],
  'Secaucus': ['Jersey City', 'Hoboken', 'Secaucus'],
}

export function getNearbyCity(city: string): string[] {
  return NEARBY_CITIES[city] ?? [city]
}